- name: install basic apt repos
  when: ansible_pkg_mgr == 'apt'
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{item}} universe
  loop:
    - "{{ansible_distribution_release}}"
    - "{{ansible_distribution_release}}-updates"

- name: install basic harmless common dependencies
  package:
    name:
    - gzip
    - python{% if ansible_python.version.major == 3 %}3{% endif %}-pip
    - python{% if ansible_python.version.major == 3 %}3{% endif %}-setuptools
    - tar
    state: present

- name: install basic harmless dependencies for apt
  when: ansible_pkg_mgr == 'apt'
  package:
    name:
    - apt-transport-https
    - iproute2
    state: present

- name: install basic harmless dependencies for RHEL
  when: ansible_os_family == 'RedHat'
  package:
    name:
    - iproute
    state: present

# Just in case we're missing the default ipv4, as explained in
# https://stackoverflow.com/a/50373356/1468388
- name: refresh facts
  setup:

- import_tasks: engine.yml
- import_tasks: swarm/main.yml
- import_tasks: app.yml
- import_tasks: compose.yml
- import_tasks: machine.yml
